services:
    axidepuy.date_helper:
        class: Axidepuy\Bundle\AxidepuyDatesDaysNameBundle\Helper\DateHelper
        public: true
        arguments: ["@translator"]

    axidepuydatesdaysnamebundle.daysname.twig_extension:
        class: Axidepuy\Bundle\AxidepuyDatesDaysNameBundle\Twig\Extension\DaysNameExtension
        public: false
        arguments: ["@axidepuy.date_helper"]
        tags:
            - { name: twig.extension }
